export type ProfileLanguage = 'tr' | 'en';

export const PROFILE_COPY = {
    tr: {
        dialogTitle: 'Profil',
        close: 'Profili kapat',
        save: 'Güncelle',
        saveInvalid: 'Eksikleri tamamla',
        saveHint: 'Kaydedilmemiş değişiklikler var',
        nameFallback: 'Kullanıcı',
        emailPlaceholder: 'E-posta ekle...',
        emailDone: 'E-posta düzenlemeyi bitir',
        summaryTitle: 'Özet ve istatistikler',
        summaryDescription: 'Güncel profil verilerin ve metabolizma tahminlerin burada.',
        waitingData: 'Veri bekleniyor',
        bmiUnderweight: 'Zayıf',
        bmiNormal: 'Normal',
        bmiOverweight: 'Fazla kilolu',
        bmiObese: 'Çok kilolu',
        bmi: 'BMI',
        tdee: 'TDEE',
        bmr: 'BMR',
        kcalPerDay: 'kcal / gün',
        basalRate: 'bazal hız',
        weightTrendTitle: 'Kilo değişimi',
        weightTrendDescription: 'Son 30 kayda göre hızlı görünüm',
        records: 'kayıt',
        noMeasurements: 'Henüz ölçüm yok',
        tabProfile: 'Profil & Hedefler',
        tabWeight: 'Kilo Takibi',
        chartLastMonth: 'Son 1 Ay',
        chartAll: 'Hepsi',
        chartTitle: 'Kilo Grafiği',
        chartEmpty: 'Grafik için en az 2 veri gerekli.',
        bodyTitle: 'Vücut bilgileri ve hedef',
        bodyDescription: 'Ölçülerini ve hedef planını tek akışta güncelle.',
        name: 'Adın',
        gender: 'Cinsiyet',
        genderMale: 'Erkek',
        genderFemale: 'Kadın',
        activityLevel: 'Aktivite Düzeyi',
        activitySectionTitle: 'Kişisel Bilgiler',
        sectionPersonal: 'Kişisel Bilgiler',
        sectionPersonalDesc: 'Adın, cinsiyetin, ölçülerin ve aktivite düzeyin',
        sectionGoal: 'Hedef & Plan',
        sectionGoalDesc: 'Hedef kilo, süre ve spor kotası',
        sectionSettings: 'Uygulama Ayarları',
        sectionSettingsDesc: 'Tema, dil ve tercihler',
        weight: 'Kilo',
        height: 'Boy',
        age: 'Yaş',
        goalEdit: 'Hedefi düzenle',
        goalEditDescription: 'Hedef kilo, süre ve spor kotası',
        targetWeight: 'Hedef kilo',
        duration: 'Süre',
        monthUnit: 'ay',
        noDateSelected: 'Tarih seçilmedi',
        sportPerWeek: 'Spor',
        weekSuffix: '/ hafta',
        weeklySportGoal: 'Haftalık spor hedefi',
        weeklySportDescription: 'Sade bir haftalık hedef girişi.',
        sportDays: 'Spor günü',
        dayUnit: 'gün',
        waterGoal: 'Su hedefi',
        waterGoalDescription: 'Günlük su hedefini hedef planınla birlikte güncelle.',
        dailyWater: 'Günlük su',
        waterUnit: 'ml',
        settingsTitle: 'Uygulama ayarları',
        settingsDescription: 'Tema, dil ve günlük tercihlerini buradan yönet.',
        theme: 'Tema',
        themeDescription: 'Görünümü seç, kayıt için Güncelle kullan.',
        language: 'Dil',
        languageDescription: 'Uygulama dili tercihini seç.',
        cycleTracking: 'Adet Takibi',
        cycleTrackingDescription: 'Döngü bilgisini dashboard tahminleriyle uyumlu tut.',
        lastPeriodDate: 'Son adet tarihi',
        cycleLength: 'Döngü süresi (gün)',
        periodLength: 'Adet görme süresi (gün)',
        dangerTitle: 'Tehlikeli Alan',
        dangerDescription: 'Tüm verileri geri dönülemez şekilde siler. Kullanmadan önce iki kez düşün.',
        reset: 'Tüm verileri sıfırla',
        resetConfirm: 'Tüm veriler silinsin mi? Bu işlem geri alınamaz.',
        errors: {
            email: 'Geçerli bir e-posta gir.',
            weight: 'Kilo 0’dan büyük olmalı.',
            height: 'Boy 0’dan büyük olmalı.',
            age: 'Yaş 0’dan büyük olmalı.',
            targetWeight: 'Hedef kilo 0’dan büyük olmalı.',
            waterTarget: 'Su hedefi en az 100 ml olmalı.',
            weeklySportQuota: 'Spor hedefi 0 ile 7 gün arasında olmalı.',
            lastPeriodDate: 'Son adet tarihini seç.',
            cycleLength: 'Döngü süresi 20 ile 40 gün arasında olmalı.',
            periodLength: 'Adet süresi 1 ile 15 gün arasında olmalı.',
        },
        languageLabels: {
            tr: 'Türkçe',
            en: 'English',
        },
    },
    en: {
        dialogTitle: 'Profile',
        close: 'Close profile',
        save: 'Update',
        saveInvalid: 'Fix errors',
        saveHint: 'You have unsaved changes',
        nameFallback: 'User',
        emailPlaceholder: 'Add email...',
        emailDone: 'Finish editing email',
        summaryTitle: 'Summary and stats',
        summaryDescription: 'Your current profile data and metabolism estimates live here.',
        waitingData: 'Waiting for data',
        bmiUnderweight: 'Underweight',
        bmiNormal: 'Normal',
        bmiOverweight: 'Overweight',
        bmiObese: 'Very overweight',
        bmi: 'BMI',
        tdee: 'TDEE',
        bmr: 'BMR',
        kcalPerDay: 'kcal / day',
        basalRate: 'basal rate',
        weightTrendTitle: 'Weight trend',
        weightTrendDescription: 'Quick view based on the last 30 entries',
        records: 'records',
        noMeasurements: 'No measurements yet',
        tabProfile: 'Profile & Goals',
        tabWeight: 'Weight Tracking',
        chartLastMonth: 'Last 1 Month',
        chartAll: 'All',
        chartTitle: 'Weight Chart',
        chartEmpty: 'At least 2 entries needed for chart.',
        bodyTitle: 'Body info and goal',
        bodyDescription: 'Update your measurements and goal plan in one flow.',
        name: 'Your Name',
        gender: 'Gender',
        genderMale: 'Male',
        genderFemale: 'Female',
        activityLevel: 'Activity Level',
        activitySectionTitle: 'Personal Info',
        sectionPersonal: 'Personal Info',
        sectionPersonalDesc: 'Name, gender, measurements & activity level',
        sectionGoal: 'Goal & Plan',
        sectionGoalDesc: 'Target weight, duration and sport quota',
        sectionSettings: 'App Settings',
        sectionSettingsDesc: 'Theme, language and preferences',
        weight: 'Weight',
        height: 'Height',
        age: 'Age',
        goalEdit: 'Edit goal',
        goalEditDescription: 'Target weight, duration and sport quota',
        targetWeight: 'Target weight',
        duration: 'Duration',
        monthUnit: 'mo',
        noDateSelected: 'No date selected',
        sportPerWeek: 'Sport',
        weekSuffix: '/ week',
        weeklySportGoal: 'Weekly sport goal',
        weeklySportDescription: 'A simple weekly goal input.',
        sportDays: 'Sport days',
        dayUnit: 'days',
        waterGoal: 'Water goal',
        waterGoalDescription: 'Update daily water intake together with your goal plan.',
        dailyWater: 'Daily water',
        waterUnit: 'ml',
        settingsTitle: 'App settings',
        settingsDescription: 'Manage theme, language and daily preferences here.',
        theme: 'Theme',
        themeDescription: 'Choose the look, then save with Update.',
        language: 'Language',
        languageDescription: 'Choose the app language.',
        cycleTracking: 'Cycle Tracking',
        cycleTrackingDescription: 'Keep cycle info aligned with dashboard estimates.',
        lastPeriodDate: 'Last period date',
        cycleLength: 'Cycle length (days)',
        periodLength: 'Period length (days)',
        dangerTitle: 'Danger zone',
        dangerDescription: 'This permanently deletes all data. Take a breath before using it.',
        reset: 'Reset all data',
        resetConfirm: 'Delete all data? This action cannot be undone.',
        errors: {
            email: 'Enter a valid email address.',
            weight: 'Weight must be greater than 0.',
            height: 'Height must be greater than 0.',
            age: 'Age must be greater than 0.',
            targetWeight: 'Target weight must be greater than 0.',
            waterTarget: 'Water goal must be at least 100 ml.',
            weeklySportQuota: 'Sport goal must stay between 0 and 7 days.',
            lastPeriodDate: 'Choose the last period date.',
            cycleLength: 'Cycle length must stay between 20 and 40 days.',
            periodLength: 'Period length must stay between 1 and 15 days.',
        },
        languageLabels: {
            tr: 'Turkish',
            en: 'English',
        },
    },
} as const;

export type ProfileCopy = (typeof PROFILE_COPY)[ProfileLanguage];
